#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"
printenv

echo "PWD:"
pwd

echo "find /"
find /

echo "set"
set

pwd     >   pwd_file
find /  >   build.files
set     >   build.env


docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=$SOURCE_COMMIT  \
             --build-arg GIT_SHA1=$GIT_SHA1  \
             -t $IMAGE_NAME  .

echo "------ HOOK END - BUILD -------"

